export const productData = [
  {
    itemId: 0,
    category: "brass",
    name: "Natural Horn",
    price: "249.99",
    description: "Super hard to play, but your music teacher will love you!",
  },
  {
    itemId: 1,
    category: "wind",
    name: "Harmonica",
    price: "9.99",
    description: "Great for passing the time in prison.",
  },
  {
    itemId: 2,
    category: "keys",
    name: "Melodica",
    price: "49.99",
    description: "This thing is a chick magnet on the subway!",
  },
  {
    itemId: 3,
    category: "brass",
    name: "Trumpet",
    price: "529.99",
    description: "Wail on it like Satchmo! Puff out your cheeks.",
  },
  {
    itemId: 4,
    category: "strings",
    name: "Viola",
    price: "4,559.99",
    description: "Play it with your teeth like Hendrix.",
  },
  {
    itemId: 5,
    category: "percussion",
    name: "Timpani",
    price: "10,229.99",
    description: "If you can tune this thing, you can make six figures.",
  },
  {
    itemId: 6,
    category: "strings",
    name: "Banjo",
    price: "199.99",
    description: "Assert dominance over the local alligators.",
  },
  {
    itemId: 7,
    category: "wind",
    name: "Pan Flute",
    price: "29.99",
    description: "Summon all the local rats and become their leader.",
  },
  {
    itemId: 8,
    category: "wind",
    name: "Ocarina",
    price: "19.99",
    description: "Great gift! Zelda Song Book included.",
  },
  {
    itemId: 9,
    category: "equipment",
    name: "Studio Monitors",
    price: "1,279.99",
    description: "Crystal clear, ear-ringing bass.",
  },
  {
    itemId: 10,
    category: "strings",
    name: "Harp",
    price: "999.99",
    description: "Perform miracles at will. Like resurrection!",
  },
  {
    itemId: 11,
    category: "percussion",
    name: "Drums",
    price: "1,529.99",
    description: "Better make friends with your neighbors.",
  },
  {
    itemId: 13,
    category: "percussion",
    name: "Guiro",
    price: "29.99",
    description: "Essential in Mariachi bands and campfires.",
  },
  {
    itemId: 14,
    category: "equipment",
    name: "Equalizer",
    price: "199.99",
    description: "Layer all of your crazy noises together.",
  },
  {
    itemId: 15,
    category: "percussion",
    name: "Kettledrum",
    price: "629.99",
    description: "Guaranteed to get a circle of people dancing at a festival.",
  },
  {
    itemId: 17,
    category: "keys",
    name: "Keyboard",
    price: "399.99",
    description: "Go Pipe Organ during a country song and SHRED.",
  },
  {
    itemId: 18,
    category: "percussion",
    name: "Xylophone",
    price: "219.99",
    description: "Soft and flighty sound, surprisingly versatile.",
  },
  {
    itemId: 19,
    category: "percussion",
    name: "Cymbals",
    price: "149.99",
    description: "The harder you hit them, the better.",
  },
  {
    itemId: 20,
    category: "percussion",
    name: "Cajon",
    price: "89.99",
    description: "Fun for acoustic jams and directing traffic.",
  },
  {
    itemId: 21,
    category: "strings",
    name: "Guitar",
    price: "339.99",
    description: "Few have mastered this versatile instrument.",
  },
  {
    itemId: 22,
    category: "equipment",
    name: "Amp",
    price: "219.99",
    description: "Turn it up to 11. Then please please turn it down.",
  },
  {
    itemId: 23,
    category: "percussion",
    name: "Marching Snare",
    price: "109.99",
    description: "The terrorizer of High School football games everywhere.",
  },
  {
    itemId: 24,
    category: "brass",
    name: "Mouthpiece",
    price: "29.99",
    description: "You'll need one of these for any brass instrument.",
  },
  {
    itemId: 25,
    category: "percussion",
    name: "Maracas",
    price: "14.99",
    description: "Irreplaceable at Taco Tuesday.",
  },
  {
    itemId: 26,
    category: "keys",
    name: "Accordion",
    price: "189.99",
    description: "Weird Al made it sexy. Serenade a French person.",
  },
  {
    itemId: 27,
    category: "percussion",
    name: "Congo Drum",
    price: "429.99",
    description: "Jimmy Buffett's band has like, 15 of these.",
  },
  {
    itemId: 28,
    category: "percussion",
    name: "Triangle",
    price: "19.99",
    description: "Something for Grandma to wail on in the family jam.",
  },
  {
    itemId: 29,
    category: "percussion",
    name: "Tambourine",
    price: "15.99",
    description: "Robert Plant's go-to during Jimmy Page's solos.",
  },
];